#!/bin/bash

###############################################################################
###############################################################################
###############################################################################

VERSION=0.1

: ${BEEFAULTS=/etc/bee.defaults}

if [ -e ${BEEFAULTS} ] ; then
    . ${BEEFAULTS}
fi

PKGMETADIR=${PKGMETADIR:-/usr/share/bee}
PKGDIR=${PKGDIR:-.}

pkg_remove_all() {
    for pkg in ${@} ; do
        pkg_remove ${pkg}
    done
}

pkg_remove() {
    search=$1
    
    # pattern is absolute path to pkg
    if [ -d ${search} ] ; then
        do_remove "${search}"
    fi
    
    # pattern is a pkg in PKGMETADIR
    if [ -d ${PKGMETADIR}/${search} ] ; then
        do_remove ${PKGMETADIR}/${search}
    fi
    
    # pattern is no installed pkg
    # show all pkgs that match pattern
    PKGS=$(find ${PKGMETADIR} -mindepth 1 -maxdepth 1 -iregex "${PKGMETADIR}.*${search}.*")
    echo "${search} matches following packages .."
    for p in $PKG ; do
        echo " -> $(basename $p)"
    done
}

do_remove() {
    pkg=$1
    
    FILES=$(/project/azubi/bee/beefind.pl --dump ${pkg}/FILES)
    
    # removing files
    for f in $FILES ; do
        # test for other pkg
        s = $(echo $f | sed -e "s,[\`|&^$.+?(){}],\\\&,g" -e "s,\[,\\\&,g" -e "s,\],\\\&,g")
        RELPKG=$(egrep "file=$f(|//.*)$" ${PKGMETADIR}/*/FILES)
        if [ 1 -eq $(echo $RELPKG | wc -w) ] ; then
            #check for directories
            if [ -d $f ] ; then
                DIR="$f $DIR"
            else
                rm -vf $f
            fi
        else
          echo "cannot remove $f .. is related to other pkgs"
        fi
    done
    
    #removing directories
    for d in $DIR ; do
        if [ -z "$(ls $d)" ] ; then
            rmdir -v $d
        fi
    done
    
    #cleaning up meta directory
    for f in `ls ${INSTALLED}` ; do
        rm -vf $f
    done
    rm -vfr ${INSTALLED}
}

pkg_remove_all $@
