#!/bin/bash

###################################################################
#  IN: ..
#
# OUT: -1 .. left greater than right
#       0 .. left equal to right
#      +1 .. left less than right

version1=$1
version2=$2

v1_space_sep=$(echo $version1 | sed -e "s,\., ,g" - )
v2_space_sep=$(echo $version2 | sed -e "s,\., ,g" - )

# check for same format
if [ $(echo $v1_space_sep | wc -w) -ne $(echo $v2_space_sep | wc -w) ] ; then
    echo "cannot compare $version1 and $version2 .. different format"
    exit 0
fi

# get shorter version number
if [ $(echo $v1_space_sep | wc -w) -lt $(echo $v2_space_sep | wc -w) ] ; then 
    cnt=$(echo $v1_space_sep | wc -w)
else
    cnt=$(echo $v2_space_sep | wc -w)
fi

# check whole versions
if [ "$version1" = "$version2" ] ; then
    echo $version1 = $version2
fi

# check parts
for p in `seq 1 $cnt` ; do
    v1=$(echo $version1 | cut -d '.' -f $p - )
    v2=$(echo $version2 | cut -d '.' -f $p - )
    
done


